server:
  port: 7777

spring:
  main:
    allow-bean-definition-overriding: true

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html