server:
  port: 8000


spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  main:
    allow-bean-definition-overriding: true
#    抽取到了nacos配置中
#  redis:
#    host: 192.168.6.200
#    password: Xqq123456
#  zipkin:
#    base-url: http://192.168.6.200:9411/
#    sender:
#      type: web
app:
  thread-pool:
    core: 4
    max: 8
    queue-size: 2000
    keep-alive-time: 300


# 暴露所有监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
