server:
  port: 9000


#数据源配置好
spring:
  zipkin:
    base-url: http://192.168.6.200:9411/
    sender:
      type: web
  datasource:
    url: jdbc:mysql://192.168.6.200:3306/gmall_product?useSSL=false&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.6.200
    password: Xqq123456

#自定义配置
app:
  minio:
    endpoint: http://192.168.6.200:9000
    ak: admin
    sk: adminadmin
    bucket-name: gmall
  thread-pool:
    core: 4
    max: 8